name: Backport

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master
jobs:
  cherry_pick_backport:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Cherry-pick
        uses: deckhouse/backport-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "release-1.0"
          labels: auto-cherry-pick
          automerge: true

          