name: Begin
on:
    push:
        branches:
            - master
            - 'release/**'
    schedule:
        # Runs at every 15th minute
        - cron: '*/15 * * * *'
    workflow_dispatch:
        inputs:
            homedrive:
                description: 'The home drive on the machine'
                default: '/home'
                required: true
            logLevel:
                description: 'Log Level'
                default: 'warning'
                type: choice
                options:
                    - info
                    - warning
                    - debug
            tag:
                description: 'Apply tag after successfull test run'
                required: true
                type: boolean
            environment:
                description: "Environment to run tests against"
                type: environment
                required: true
                
jobs:    
    testJob:
        runs-on: ubuntu-22.04
        steps:
            - run: |
                echo "Hello world!"
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: List files in repository
              run: |
                echo "The repository ${{ github.repository }} contains the following files:" tree
            - run: |
                echo "Homedrive ${{ inputs.homedrive }}"
                echo "LogLevel ${{ inputs.logLevel }}"
                echo "Tag ${{ inputs.tag }}"
                echo "Environment ${{ inputs.environment }}"
              name: Workflow inputs
              if: ${{ github.event_name == 'workflow_dispatch' }}
    test2:
        runs-on: ubuntu-22.04
        needs: testJob
        steps:
            - run: |
                echo "Job: ${{ github.job }}"

    test3:
        runs-on: ubuntu-22.04
        needs: [testJob, test2]
        steps:
            - run: |
                echo "Job: ${{ github.job }}"

