name: Echo github variables
on: 
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: first
        uses: actions/github-script@v7
        with:
          script: |
            console.log(github.event)

            console.log(context)
