name: Echo github variables
on: 
  workflow_dispatch: 
  pull_request:
    types: [opened, edited, closed, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: first
        uses: actions/github-script@v7
        with:
          script: |
            console.log(github.event)

            console.log(context)

            if (context.payload.sender.login == 'Steamvis') {
              console.log('here');
            }
            
