name: Exit with error
on: 
  workflow_dispatch: 
  push:    
  pull_request_target:
    branches: 
      - master
jobs:
  exit:
    runs-on: ubuntu-latest
    steps:
      - name: exit with error
        run: exit 1
