name: Test
on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    testJob:
        runs-on: ubuntu-22.04
        steps:
            - run: |
                echo "Hello world!"
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: List files in repository
              run: |
                echo "The repository ${{ github.repository }} contains the following files:" tree