name: Secrets
on: 
  workflow_dispatch: 
jobs:
    secret:
      runs-on: ubuntu-latest
      steps:
        - name: Echo Secrets
          run: |
            echo "${{ secrets.ENV_SECRET }}"
            echo "${{ secrets.MY_SECRET }}"
