name: Sleep job
on:
  workflow_dispatch: 
    inputs:
      sleepTime:
        type: number
        default: 300
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: sleep ${{ inputs.sleepTime }} seconds
        run: sleep ${{ inputs.sleepTime }}
