name: wait job complete
on: 
  pull_request: 
    types: [opened, synchronize, reopened, edited]
jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.inputs.ci_commit_ref_name;
            const prNum = context.payload.inputs.issue_number;
            console.log(`Check build workflow is completed for branch: ${branchName} PR: ${context.payload.repository.html_url}/pull/${prNum}`);

            const waitForWorkflowIsCompleted = require('./js_scripts/validate-workflow-is-ready')({ github, context, core });
            try {
              await waitForWorkflowIsCompleted(branchName, 'Build and test for dev branches'))
            } catch(error)
              core.setFailed(error);
            }